# Generated by Django 5.2 on 2025-04-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Examents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Categorie Exament',
                'verbose_name_plural': 'Categories Examents',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('date_enregistrement', models.DateField()),
                ('pieces_identite', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PAS', 'Passeport'), ('PER', 'Permis de Conduire'), ('AUT', 'Autre')], max_length=3)),
                ('numero_identite', models.CharField(max_length=50)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('images', models.ImageField(blank=True, upload_to='media/patient_images')),
                ('pieces_jointes', models.FileField(blank=True, upload_to='media/patient_files')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Examents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_exament', models.CharField(max_length=520)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, upload_to='media/exament_images')),
                ('pieces_jointes', models.FileField(blank=True, upload_to='media/exament_files')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.categories_examents')),
            ],
            options={
                'verbose_name': 'Exament',
                'verbose_name_plural': 'Examents',
            },
        ),
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture', models.BooleanField(default=False)),
                ('date_analyse', models.DateField(auto_now_add=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='media/analyse_files')),
                ('exament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.examents')),
                ('prix', models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses_prix', to='analyse.examents')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.patients')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('total', models.IntegerField(editable=False)),
                ('payé', models.BooleanField(default=False)),
                ('versement', models.IntegerField()),
                ('balance', models.IntegerField(editable=False)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='media/facture_files')),
                ('numero_facture', models.CharField(editable=False, max_length=1000)),
                ('analyses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_analyses', to='analyse.analyses')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.patients')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('date_resultat', models.DateField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/resultat_images')),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='media/resultat_files')),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.analyses')),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultats',
            },
        ),
    ]
